README.md

Add NG Informática

---

README.md

add glamorous to onemarket.com.br

---

README.md

Trabalhamos na nossa startup com Rails e React.

add HomeTeam

---

README.md

🎉 
Let me know if I need to change anything before merging

Add Astrocoders

---

README.md

We do use React in a lot of products, mainly our Webplayer www.superplayer.fm.
Also, we are using GraphQL in some APIs.

Adding Superplayer.

---

README.md

Add Jest and Meteor.
https://fractalflows.com was created with Meteor + React 👍

Add more techs used in Astrocoders

---

README.md

As asked, added specific tech.

Fred's specific tech

---

README.md

Nas techs do Fred faltou o principal: React!

Added React to Fred

---

README.md

Added Pague Menos

---

README.md

Olá, pessoal.
Eu trabalho na M4U e nós também utilizamos React.

Added M4U company

---

README.md

Adicionando empresa arizona e reordenando algumas da lista

add arizona

---

README.md

Add VML Brasil to list

---

README.md

add Brasal labs to companies with use react tecnologies

add Brasal labs to companies with use react tecnologies

---

README.md

updating readme.md including the current place i work.

including Menthor company

---

README.md

Add Printi to companies that use React in Brazil

Add Printi

---

README.md

Solicitando implementar a empresa onde sou dev e utilizamos no seguimento iOT.

Implementar Empresa Automi

---

README.md

-Alterado o link para o site que a Globo utiliza para divulgar suas vagas e falar da empresa em si.
-Adicionando React Native como tecnologia utilizada de acordo com vaga postada pela própria empresa. 
Fonte:
(https://www.lovemondays.com.br/vagas/vaga-de-desenvolvedor-a-react-native-globo-rio-de-janeiro-rj-1061939 e https://talentos.globo.com/#/oportunidades/desenvolvedor-a-react-native/mp0mu5i) 
*Pode servir para quem esteja interessado em se candidatar.

Alterando o link da Globo.com e adicionando a tecnologia utilizada

---

README.md

Inclusão de empresas segundo divulgação de vagas das mesmas, onde contam que trabalham com React.

Inclusão de empresas 

---

README.md

Houve uma tentativa de incluir um tópico de vagas, porém voltei atrás por enquanto.

Inclusão da empresa Krush e a startup Escalaí .

---

README.md

Add elomilhas

---

README.md

Adicionando as tecnologias utilizadas no ecossistema React na MATERA.

Adicionando tecnologia MATERA Systems

---

README.md

Adicionando o site Buscapé para a lista

Adding Buscape to the list

---

README.md

Segundo as vagas disponibilizadas:
Cedro Technologies - https://github.com/react-brasil/vagas/issues/15
MaxMilhas - https://github.com/react-brasil/vagas/issues/14 
Isobar Brasil - https://github.com/react-brasil/vagas/issues/12
EcoStage - https://github.com/react-brasil/vagas/issues/6
Easy Carros - https://github.com/react-brasil/vagas/issues/5

Inclusão das empresas Cedro , MaxMilhas, Isobar Brasil, EcoStage e Easy Carros

---

README.md

Adição da empresa Cubos à lista de empresas.

docs: add Cubos to the companies list

---

README.md

- Atualização do stack
- Movida de empresa para projetos

BibliaOnline

---

README.md

Add empresa Goomer

---

README.md

Add eMasters

---

README.md

[Diebold Nixdorf](https://www.dieboldnixdorf.com.br/) utiliza React em algumas aplicações.

Adicionando a Diebold Nixdorf na lista

---

README.md

Adiciona UPX Technologies de Campinas, SP.

---

README.md

Adicionando a Getup Cloud

---

README.md

Adicionei a empresa Wizard à lista, mencionando as tecnologias utilizadas no app dedicado aos alunos do curso de inglês.

adicionado empresa Wizard referenciando as tecs utilizadas em seu app

---

README.md

Incluida Junto Seguros

---

README.md

Adicionado:
- Enzyme
- Immutable
- Jest
- Reselect
- Saga
- Styled Components

Atualizado Tecnologias da Eskolare

---

README.md

Add new company GeekHunter, with location and technologies.

Add company GeekHunter

---

README.md

add Invillia into list

---

README.md

there’s no city because our work is done remotely 😄🗺

add kunst.com.br

---

README.md

Inserir Agência Antidoto Design

---

README.md

Incluído a empresa Teclógica de Blumenau, SC.

Incluído Teclógica - Blumenau - SC

---

README.md

A Evolux é uma empresa que atua em dois nichos de desenvolvimento de software, ambos B2B: na produção e manutenção de aplicações para call centers; e na fabricação outsourcing de produtos web de alguma forma relacionados a telefonia. As soluções têm centenas de milhares de usuários ativos ao redor do mundo, considerável engajamento em projetos free source, além de financiamento e organização de comunidades locais de JavaScript e Python. (E sempre atualizando seu selo de Great Place do Work :smile:)

add evolux

---

README.md

A Pluks é uma start up encubado pela MGTI - Funsoft em BH.
Com objetivo de agilizar e desburocratizar os atendimentos nos eventos, o nosso produto traz ao usuário o poder de compra em mãos com um PDV móvel, o seu celular.

Incluido Pluks Start up em BH

---

README.md

adiciona Geru

---

README.md

Adicionando empresa na qual faço parte, atualmente trabalhamos com ReactJS e periféricos.

Adição de empresa

---

README.md

Adding the company and stack REACT-NATIVE that we've been working on.

Adding new company

---

README.md

Adicionado Alumy na lista de projetos brasileiros que usam React.

Adicionado Alumy

---

CONTRIBUTING.md
MOBILE.md
README.md

Design para Mobile

---

MOBILE.md
README.md

* Insere Next.js como uma tecnologia que usamos
* Ordena alfabeticamente a lista

Atualiza Vinta Software

---

MOBILE.md
README.md

Remoção da arena.im, pois é uma empresa da california. Adicionando a Softbox. Maior empresa de TI de uberlândia.

Removendo arena.im e adicionando softbox

---

MOBILE.md
README.md

Nova empresa: Serasa consumidor

---

MOBILE.md
README.md

Add Go Backlog

---

MOBILE.md
README.md

Include Teravoz

---

MOBILE.md
README.md

chore: add vntrx.com

---

MOBILE.md
README.md

added liv up new technologies

---

MOBILE.md
README.md

Add Unbanked Pagamentos

---

MOBILE.md
README.md

Add KeepClear

---

MOBILE.md
README.md

- [] Me comprometo a lançar um PR em https://github.com/graphql-brasil/empresas-que-usam-graphql-no-brasil

Incluindo Kiper

---

MOBILE.md
README.md

FW7 Soluções

---

MOBILE.md
README.md

Add Secrel

---

MOBILE.md
README.md

Add Fortbrasil

---

MOBILE.md
README.md

add venda.la

---

MOBILE.md
README.md

Add SumUp to companies list

---

MOBILE.md
README.md

App2Sales no longer exists

---

MOBILE.md
README.md

Add new company

---

MOBILE.md
README.md

Add Fundação CERTI

---

MOBILE.md
README.md

Add Leroy Merlin Brasil

---

PULL_REQUEST_TEMPLATE.md

Correção de um pequeno `typo` dentro do arquivo `PULL_REQUEST_TEMPLATE.md` :)

fix: fix typo on Pull Request Template

---

MOBILE.md
README.md

Add Agrotools

---

MOBILE.md
README.md

feat: add gamers club

---

MOBILE.md
README.md

add StartSe company

---

MOBILE.md
README.md

Adicionado startup Seo Zé

---

MOBILE.md
README.md

Adiconar tecnologias da Magnetis

---

MOBILE.md
README.md

Add DevGrid

---

MOBILE.md
README.md

Add MAiS Resultados na lista

---

MOBILE.md
README.md

Adding CITi to the list

---

MOBILE.md
README.md

Add E-core

---

MOBILE.md
README.md

Add more technologies to GreenMile

---

MOBILE.md
README.md

Adding Zaal Tecnologia

---

MOBILE.md
README.md

Adicionando novas tecnologias a Cheesecake Labs

---

CONTRIBUTING.md
MOBILE.md
README.md

Adicionar representação de trabalho remoto no registro da Magnetis.
closes: #297

Adicionar coluna com tipo de contrato

---

MOBILE.md
README.md

add DEX Company

---

MOBILE.md
README.md

Add company 

---

MOBILE.md
README.md

Inclusão do Nexo Jornal, lançamos no ar uma nova versão de nosso site utilizando React.

chore: adicionando Nexo Jornal à lista de empresas

---

MOBILE.md
README.md

Add Novatics

---

MOBILE.md
README.md

Update digital innovation one

---

MOBILE.md
README.md

Add empresa Juntos Somos Mais

---

README.md

Pull request Gen - General Shopping

---

MOBILE.md
README.md

Add Ochain

---

MOBILE.md
README.md

Adicionada nova empresa Simplifica CI na parte de React Nativa (Mobile)

Adicionada nova empresa: Simplifica CI

---

MOBILE.md
README.md

Add Voltbras

---

MOBILE.md
README.md

Add  SENAC/SE e Popcode

---

MOBILE.md
README.md

Add Caju Beneficios

---

MOBILE.md
README.md

Adicionando empresa

---

MOBILE.md
README.md

Adicionando empresa Ponto GO

---

MOBILE.md
README.md

adding acerta promotora on list

---

MOBILE.md
README.md

adicionado tres novas empresas

---

MOBILE.md
README.md

Adding Contraktor

---

MOBILE.md
README.md

---
Não coloquei o tipo do contrato, pois, além de não ter certeza, acredito que a política mude por causa da COVID.

Add Creditas

---

MOBILE.md
README.md

Adicionada empresa MoutS

---

MOBILE.md
README.md

Inclusão da empresa Riachuelo.

Add Riachuelo

---

MOBILE.md
README.md

Add ServiceNet and Softcon from João Pessoa. Add info in Fractal Tecnologia.

---

MOBILE.md
README.md

add Magapay

---

MOBILE.md
README.md

add Magazord

---

MOBILE.md
README.md

- [*] Lí o CONTRIBUTING.md
- [*] Coloquei em ordem alfabética
- [*] Atualizei o arquivo README.md
- [*] Atualizei o arquivo MOBILE.md
- [*] Me comprometo a lançar um PR em https://github.com/graphql-brasil/empresas-que-usam-graphql-no-brasil
- [*] Esta empresa não utiliza GraphQL

Add Mapfry

---

MOBILE.md
README.md

Adicionando RankMyAPP

---

README.md

- [ x ] Lí o CONTRIBUTING.md
- [ x ] Coloquei em ordem alfabética
- [ x ] Atualizei o arquivo README.md
- [ x ] Atualizei o arquivo MOBILE.md
- [ x ] Esta empresa não utiliza GraphQL

Migração completa de softbox para luizalabs

---

MOBILE.md
README.md

Add Luizalabs Franca SP

---

MOBILE.md
README.md

add Lambda3

---

MOBILE.md
README.md

Add GetNet

---

MOBILE.md
README.md

- [ x ] Lí o CONTRIBUTING.md
- [ x ] Coloquei em ordem alfabética
- [ x ] Atualizei o arquivo README.md
- [ x ] Esta empresa não utiliza GraphQL

Adicionar empresa bowe de uberlândia

---

MOBILE.md
README.md

adding wa project

---

MOBILE.md
README.md

Add Irriga Global

---

MOBILE.md
README.md

Add Seasoned

---

MOBILE.md
README.md

Added Poupachef to list of companies

---

MOBILE.md
README.md

Adicionei o projeto da [Fábrica de Software](https://github.com/fabsoftwareifrs) do [IFRS](https://ifrs.edu.br/)!
O projeto Fábrica de Software é um grupo de bolsistas e voluntários que desenvolvem aplicações open source para a educação utilizando a Stack Node e React o atual projeto é o desenvolvimento de um Software de Gestão de Biblioteca ILS (Integrated Library System) que será open source e utilizará fronte-end 100% React, além de projetos futuros que serão desenvolvidos na Stack!
Atualmente temos apenas a descrição da tarefa de entrada no projeto e um quickstart de node com GraphQL, mas iremos postar o Sistema de Bibliotecas em breve e os futuros projetos assim que eles forem sendo desenvolvidos!
Contribuições e …

Adicionei o projeto da Fábrica de Software do IFRS

---

MOBILE.md
README.md

Add Salvus

---

MOBILE.md
README.md

Update ReadMe e Mobile.md

---

MOBILE.md
README.md

Add BIMachine

---

MOBILE.md
README.md

bemcare - react

---

MOBILE.md
README.md

create UAUBox info

---

MOBILE.md
README.md

Agenda Edu

---

MOBILE.md
README.md

Adiciona Quóro

---

MOBILE.md
README.md

Add Sky.One

---

MOBILE.md
README.md

Adicionando a Eyemobile

---

MOBILE.md
README.md

Adicionando Volanty

---

MOBILE.md
README.md

- [ x] Lí o CONTRIBUTING.md
- [ x] Coloquei em ordem alfabética
- [ x] Atualizei o arquivo README.md
- [ x] Atualizei o arquivo MOBILE.md
- [ x] Esta empresa não utiliza GraphQL

Adicionando Mudi Saúde

---

MOBILE.md
README.md

Adicionado Vialaser

---

MOBILE.md
README.md

Add DokeHost

---

MOBILE.md
README.md

Adicionando nova empresa - Paytrack

---

MOBILE.md
README.md

feat(company): add Origin Financial as company

---

MOBILE.md
README.md

Add Croct company

---

MOBILE.md
README.md

Add Bionexo company

---

MOBILE.md
README.md

Add Nodo company

---

MOBILE.md

Corrigi a cidade da BH Servers.

Correção BH

---

MOBILE.md
README.md

Adding RD Station company

---

MOBILE.md
README.md

Inclusão da empresa Parnity na lista

---

MOBILE.md
README.md

Add Afya to list

---

MOBILE.md
README.md

add rumo soluções

---

MOBILE.md
README.md

- [ ✔️  ] Lí o CONTRIBUTING.md
- [ ✔️ ] Coloquei em ordem alfabética
- [ ✔️ ] Atualizei o arquivo README.md
- [ ✔️ ] Atualizei o arquivo MOBILE.md
- [ ✔️ ] Esta empresa não utiliza GraphQL

Adição da empresa Descomplica nas listas dos arquivos README.md e MOBILE.md

---

MOBILE.md
README.md

Add Objective Company

---

MOBILE.md
README.md

- [ X] Lí o CONTRIBUTING.md
- [ X] Coloquei em ordem alfabética
- [ X] Atualizei o arquivo README.md
- [ X] Atualizei o arquivo MOBILE.md
- [ X] Esta empresa não utiliza GraphQL

Update ecossystem acerta promotora

---

MOBILE.md
README.md

add cuidas

---

MOBILE.md
README.md

Nexodata add to list

---

MOBILE.md
README.md

Adicionar duas empresas mineiras que utilizam o React

---

MOBILE.md
README.md

Add quero2pay to list!

---

MOBILE.md
README.md

Add AME Digital to list

---

MOBILE.md
README.md

Add Axur to list!

---

MOBILE.md
README.md

Add Onbank to list!

---

MOBILE.md
README.md

update techs OLX

---

MOBILE.md
README.md

Add Education Journey to list

---

MOBILE.md
README.md

Add Apllos to list!

---

MOBILE.md
README.md

Add Webmotors to list!

---

MOBILE.md
README.md

Add Banco Inter to list!

---

MOBILE.md
README.md

Add Stone to list!

---

MOBILE.md
README.md

Add Pão de açúcar to list!

---

.github/PULL_REQUEST_TEMPLATE.md
MOBILE.md
README.md

Adicionando empresa enContact

---

MOBILE.md
README.md

Add Polishop to list

---

MOBILE.md
README.md

Add Nata.House to list

---

MOBILE.md
README.md

Adding Joyjet

---

MOBILE.md
README.md

Adding Portão 3

---

MOBILE.md
README.md

- [x ] Lí o CONTRIBUTING.md
- [x ] Coloquei em ordem alfabética
- [x ] Atualizei o arquivo README.md
- [x ] Atualizei o arquivo MOBILE.md
- [x ] Me comprometo a lançar um PR em https://github.com/graphql-brasil/empresas-que-usam-graphql-no-brasil

⚛️ update: Nexo Jornal stack

---

MOBILE.md
README.md

feat: adding Enext

---

MOBILE.md
README.md

feat: add zenklub

---

MOBILE.md

Adding Woovi in List Mobile

---

MOBILE.md

Nova empresa que usa React no Brasil
